apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: service
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: ai-care
    app.kubernetes.io/component: service-account
