services:
  local-db:
    image: postgres:17.9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aicare
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - ./postgres/local-init.sql:/docker-entrypoint-initdb.d/01-local-init.sql:ro
      - local_pg_data:/var/lib/postgresql/data

  auth-user-service:
    build:
      context: ./apps/auth-user-service
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - local-db
      - onprem-sensitive-api

  questionnaire-service:
    build:
      context: ./apps/questionnaire-service
    ports:
      - "8082:8080"
    env_file:
      - .env
    volumes:
      - ${USERPROFILE}/.aws:/root/.aws:ro
    depends_on:
      - local-db
      - onprem-sensitive-api

  board-service:
    build:
      context: ./apps/board-service
    ports:
      - "8083:8080"
    env_file:
      - .env
    depends_on:
      - local-db

  ai-triage-service:
    build:
      context: ./apps/ai-triage-service
    ports:
      - "8084:8080"
    env_file:
      - .env
    volumes:
      - local_reports:/app/local-reports
      - ${USERPROFILE}/.aws:/root/.aws:ro
    depends_on:
      - local-db

  hospital-recommendation-service:
    build:
      context: ./apps/hospital-recommendation-service
    ports:
      - "8085:8080"
    env_file:
      - .env

  onprem-sensitive-api:
    build:
      context: ./apps/onprem-sensitive-api
    ports:
      - "8086:9000"
    env_file:
      - .env
    depends_on:
      - local-db

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "8080:80"
    depends_on:
      - auth-user-service
      - questionnaire-service
      - board-service
      - ai-triage-service
      - hospital-recommendation-service

volumes:
  local_pg_data:
  local_reports:
