apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: service
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: ai-care
    app.kubernetes.io/component: service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::105959916837:role/ai-care-dev-backend-irsa-role
