apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base에 있는 기본 뼈대를 그대로 가져옵니다.
resources:
- ../../../base/auth-user-service

# 개발 환경만의 특별한 설정
namePrefix: dev-
replicas:
- count: 2
  name: auth-user-service
images:
- name: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/auth-user-service:latest
  newName: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/auth-user-service
  newTag: 599a1d3b4428e58d27bb1111be51e52bcad01ff2
