apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base에 있는 기본 뼈대를 그대로 가져옵니다.
resources:
- ../../../base/board-service

# 개발 환경만의 특별한 설정
namePrefix: dev-
replicas:
- count: 2
  name: board-service
images:
- name: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/board-service:latest
  newName: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/board-service
  newTag: b795b2947c66983c9a7c5e083f256932e1e90dc5
patches:
- path: serviceaccount-delete-patch.yaml
- path: serviceaccountname-patch.yaml
