apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-user-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/parkjiwon-2580/AIcloud.git'
    targetRevision: cicd/0608
    path: manifests/overlays/dev/auth-user-service # 👈 경로 확인!
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true