apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    - rolearn: arn:aws:iam::105959916837:role/ai-care-dev-eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::105959916837:user/hyeongwook
      username: hyeongwook
      groups:
        - system:masters

    - userarn: arn:aws:iam::105959916837:user/honghee
      username: donghee
      groups:
        - system:masters

    - userarn: arn:aws:iam::105959916837:user/jiwon
      username: jiwon
      groups:
        - system:masters

    - userarn: arn:aws:iam::105959916837:user/jiyun
      username: jiyun
      groups:
        - system:masters
