apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/frontend

# 개발 환경 설정 (보통은 Prefix를 안 붙이거나 dev- 를 붙임)
# namePrefix: dev-  (필요하다면 주석 해제)

replicas:
- count: 2
  name: frontend
images:
- name: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:latest
  newName: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-service
  newTag: c27d6d5b1f95809ac9bb82f0e0ced59b8ec982b7

patches:
- path: ingress-backends-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: frontend-ingress
    version: v1
