apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: service
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: ai-care
    app.kubernetes.io/component: ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-user-service
                port:
                  number: 80

          - path: /me
            pathType: Prefix
            backend:
              service:
                name: auth-user-service
                port:
                  number: 80

          - path: /info
            pathType: Prefix
            backend:
              service:
                name: board-service
                port:
                  number: 80

          - path: /ai
            pathType: Prefix
            backend:
              service:
                name: ai-triage-service
                port:
                  number: 80

          - path: /hospitals
            pathType: Prefix
            backend:
              service:
                name: hospital-recommendation-service
                port:
                  number: 80

          - path: /questionnaires
            pathType: Prefix
            backend:
              service:
                name: questionnaire-service
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
