apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  # 만약 SSL(HTTPS)을 적용한다면 아래 주석을 해제하고 인증서 ARN을 넣습니다.
  # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:xxxxx:certificate/xxxx
spec:
  ingressClassName: alb # 👈 구형 애노테이션 대신 여기에 명시하는 것이 최신 표준입니다!
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80