apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base에 있는 기본 뼈대를 그대로 가져옵니다.
resources:
- ../../../base/questionnaire-service

# 개발 환경만의 특별한 설정
namePrefix: dev-
replicas:
- count: 2
  name: questionnaire-service
images:
- name: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/questionnaire-service:latest
  newName: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/questionnaire-service
  newTag: e45e03ac6f1b691a8ef3357b8d7aa0a19dabd9bb
patches:
- path: serviceaccount-delete-patch.yaml
- path: serviceaccountname-patch.yaml
