apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base에 있는 기본 뼈대를 그대로 가져옵니다.
resources:
- ../../../base/questionnaire-service

# 개발 환경만의 특별한 설정
namePrefix: dev-
replicas:
- count: 2
  name: questionnaire-service
images:
- name: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/questionnaire-service:latest
  newName: 105959916837.dkr.ecr.ap-northeast-2.amazonaws.com/questionnaire-service
<<<<<<< HEAD
  newTag: 2a10d76323b8b877c4169bbdccaf8075a25cf707
=======
  newTag: 1d8ee194bc0d778cefce9ea803f9381c7cf44047
>>>>>>> ea662afa2fb91e29e5af6f954d0097b0269dab24
