name: monitoring

on:
  push:
    branches:
      - monitoring

jobs:
  monitoring-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create .env file
        run: touch .env
      - name: Validate Docker Compose
        run: docker compose config
      
      - name: Notify Slack 
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C0B1DKTGCLQ'
          payload: |
            {
              "text": "✅ Deployment to production succeeded"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
